# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51c89c84946ba9e6b2792993119e0228f83a41b1ef42a3b3c71f3d4f84ee53fdace0f829d388c3d612e3acc892f0a603afba09a7beb30043bc572656ce27b274

test:
  secret_key_base: e229cd29c5894b2770206cb8b36c690ebe262e900a40aa50333026ca53408119347fd18606bd2d2072add35645f2570c57de042de00282ee6e4c2ac544ff86b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
